# Site settings
title: Don't learn this
email: pablerass@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Please, avoid learn this.
baseurl: ""
url: "http://blog.dontlearnthis.com"
twitter_username: pab1eras
github_username:  pablerass

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-mentions
