# Site settings
title:  Don't learn this
description: > # this means to ignore newlines until "baseurl:"
  Please, avoid learn this. This is only an advice you should not learn from.
baseurl: ""
url: "http://please.dontlearnthis.com"
title_image: "http://www.gravatar.com/avatar/33c5e53bc9f904769c56ce8f12a37f07?s=500&d=mm"

github_repository: https://github.com/pablerass.github.io
post_limit: 6

# Author information
email:  pablerass@gmail.com
author: Pablo Mu&ntilde;oz
about:

# Infrastructure accounts
google_analytics: "UA-42974454-2"
disqus_account:   dontlearnthis
addthis_id:       ra-51fffcfc4188020d

# Social usernames/URLs
twitter_username: pab1eras
github_username:  pablerass
linkedin_link:    https://es.linkedin.com/in/pmorbananos
#google_plus_link: https://plus.google.com/105692111327986966802

# Footer
footer_left: "Licensed under &nbsp;<a rel=\"license\" href=\"http://creativecommons.org/licenses/by/4.0/\"><i class=\"fa fa-cc\"></i> by 4.0</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/pablerass/pablerass.github.io\">Github Page</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-mentions

