# Site settings
title: Don't learn this
email: pablerass@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Please, avoid learn this. This is only an advice you should not learn.
baseurl: ""
url: "http://please.dontlearnthis.com"
title_image: "http://www.gravatar.com/avatar/33c5e53bc9f904769c56ce8f12a37f07?s=500&d=mm"

google_analytics: "UA-42974454-2"

# Build settings
github_repository: https://github.com/pablerass.github.io
post_limit: 5

# Social usernames/URLs
twitter_username: pab1eras
github_username:  pablerass
linkedin_link:    https://es.linkedin.com/in/pmorbananos
google_plus_link: https://plus.google.com/105692111327986966802

# Footer
footer_left: ""
footer_center: "Made a movida loca"
footer_right: ""

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-mentions

