# Site settings
title:  Don't learn this
description: > # this means to ignore newlines until "baseurl:"
  Please, avoid learn this. This is only an advice you should not learn from.
baseurl: ""
url: "http://please.dontlearnthis.com"
title_image: "http://www.gravatar.com/avatar/33c5e53bc9f904769c56ce8f12a37f07?s=500&d=mm"

github_repository: https://github.com/pablerass.github.io
post_limit: 6

# Author information
email:  pablerass@gmail.com
author: Pablo Mu&ntilde;oz
about: >
  <p>I am a computer engineer and this is my first technology blog.</p>

  <p>Blog posts will talk about DevOps, agile methodologies, databases,
  programming or whatever that seemed to me interesting to write about</p>

  <p>I pretend to use this mean to write in English, to learn and to enjoy, not
  to teach. Read it if you want, extract any information you think could be
  interesting but contrast it and get your own conclusions, as you should do
  always with everything.</p>

  <p>If you are interested, you can find more about me in the links just
  above this text.</p>

# Infrastructure accounts
google_analytics: "UA-42974454-2"
disqus_account:   dontlearnthis
addthis_id:       ra-51fffcfc4188020d

# Social usernames/URLs
twitter_username: pab1eras
github_username:  pablerass
linkedin_link:    https://es.linkedin.com/in/pmorbananos
#google_plus_link: https://plus.google.com/105692111327986966802

# Footer
footer_left: "Licensed under &nbsp;<a rel=\"license\" href=\"http://creativecommons.org/licenses/by/4.0/\"><i class=\"fa fa-cc\"></i>&nbsp; by 4.0</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/pablerass/pablerass.github.io\">GitHub Pages &nbsp;<i class=\"fa fa-github-alt\"></i></a>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-mentions

